# ==============================================================
# 1. IDENTITÉ ET PORT
# ==============================================================
spring.application.name=User-Service
server.port=8081

# Désactivation du Config Server (évite l'erreur spring.config.import)
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Désactivation de Eureka pour le test local (optionnel)
eureka.client.enabled=false

# ==============================================================
# 2. CONFIGURATION DE LA BASE H2 (En mémoire)
# ==============================================================
# La base sera créée automatiquement en mémoire sous le nom 'doctorat_db'
spring.datasource.url=jdbc:h2:mem:doctorat_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2 : accessible sur http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Pour que la console s'affiche malgré Spring Security
spring.h2.console.settings.web-allow-others=true

# ==============================================================
# 3. JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==============================================================
# 4. SÉCURITÉ (JWT)
# ==============================================================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000