server.port=8888
spring.application.name=config-service

# Profile native pour utiliser le système de fichiers local
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///c:/Users/pc/Desktop/DOCTORAL_MANAGEMENT/doctorat-management-platform/config-service/config-repo

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
